#!/bin/sh

spool_dir=/var/spool/envoy
processed_dir=$spool_dir/processed

cd "$(dirname "$0")"
mkdir -p $processed_dir

for x in /var/spool/envoy/*.xml; do
	[[ -f $x ]] || continue

	echo "Processing $x."
	$HOME/bottle/bin/python import.py --dburi "sqlite:///$HOME/envoy.db" $x &&
		{
		gzip $x
		mv $x.gz $processed_dir
		}
done

